### PR TITLE
Forum fixes

### LINKED ISSUE #103: Discussion creation won't currently actually work
Discussion store will simply create a discussion, but when creating a discussion the first post will also need creating with the content passed through.

### PR DESCRIPTION
**Pull request by AndreasElia**
This fixes #103 and #125 as well as a few other things.

### CODE REVIEW

File: src/Controllers/DiscussionController.php [hunk 1]
```diff
@@ -37,9 +37,20 @@ public function create()
...
     {
-        $request['slug'] = str_slug($request->title, '-');
+        $discussion = Discussion::create($request->only([
+            'title',
+        ]) + [
+            'user_id' => $request->user()->id,
+            'slug'    => str_slug($request->title, '-'),
+        ]);
 
-        $discussion = Discussion::create($request->all());
```
Comment (Dylan-DPC) [inline src/Controllers/DiscussionController.php]: Why `create` in one place and `attach` in the other in the same fn? Better to use the same thing for consistency

File: src/Controllers/DiscussionController.php [hunk 2]
```diff
@@ -53,7 +64,7 @@ public function store(CreateDiscussionRequest $request)
      */
     public function show(Discussion $discussion)
     {
-        $discussion->posts = $discussion->posts()->paginate(config('pagination.posts'));
```
Comment (Dylan-DPC) [inline src/Controllers/DiscussionController.php]: Why is config selection removed?

Comment (AndreasElia) [inline src/Controllers/DiscussionController.php]: Was a mistake, will fix it later.
